[package]
name = "cherry-rs"
version = "0.1.0"
authors = ["Kyle M. Douglass <kyle.m.douglass@gmail.com>"]
repository = "https://github.com/kmdouglass/cherry"
edition = "2021"
description = "Tools for designing sequential optical systems"
license-file = "LICENSE.txt"

[lib]
crate-type = ["lib"]

[dependencies]
anyhow = "1.0"
ndarray = { version = "0.15", features = [ "serde" ] }
serde = { version = "1", features = [ "derive" ] }

[dev-dependencies]
approx = { version = "0.5" }
ndarray = { version = "0.15", features = [ "approx-0_5", "serde" ] }
