[package]
name = "cherry-rs"
version = "0.1.0"
authors = ["Kyle M. Douglass <kyle.m.douglass@gmail.com>"]
repository = "https://github.com/kmdouglass/cherry"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
anyhow = "1.0"
serde = { version = "*", features = ["derive"] }
