name: Build Rust WASM and JS Bundle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly-2026-02-20
        targets: wasm32-unknown-unknown
        components: rust-src

    - name: Install wasm-pack and wasm-bindgen-cli
      run: | 
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        cargo install wasm-bindgen-cli

    - name: Test cherry-rs Rust lib
      working-directory: ./raytracer/
      run: |
        cargo test -p cherry-rs

    - name: Test cherry-js Rust lib
      working-directory: ./raytracer/
      run: |
        cargo test -p cherry-js --target wasm32-unknown-unknown